"""
Compose the M3 ensemble uncertainty panels into publication-ready figures.

Purpose
-------
Assemble the three uncertainty source panels generated by
``68_make_uncertainty_figures.py`` into:
- the original compact publication composite; and
- the framed ``pretty`` composite used as the canonical release figure.

Inputs
------
Read from ``outputs/figures/``:
- ``m3_uncertainty_vs_error.png``
- ``m3_uncertainty_deciles_mae.png``
- ``m3_abstention_curve.png``

Outputs
-------
Written under ``outputs/figures/final/``:
- ``final_uncertainty_publication.png/.pdf``
- ``final_uncertainty_publication_pretty.png/.pdf``

Notes
-----
This script only composes already-generated scientific panels. Numerical values
are produced upstream by the ensemble evaluation and base-figure scripts.
"""

from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.patches import FancyBboxPatch


ROOT = Path(__file__).resolve().parents[2]

SRC = ROOT / "outputs/figures"
OUT = ROOT / "outputs/figures/final"

OUT.mkdir(
    parents=True,
    exist_ok=True,
)

paths = {
    "A": SRC / "m3_uncertainty_vs_error.png",
    "B": SRC / "m3_uncertainty_deciles_mae.png",
    "C": SRC / "m3_abstention_curve.png",
}

for label, path in paths.items():
    if not path.exists():
        raise FileNotFoundError(
            f"Missing panel {label}: {path}"
        )

images = {
    label: mpimg.imread(path)
    for label, path in paths.items()
}


def crop_panel_title(image, top_fraction=0.12):
    """Remove the source-panel title area before placing it in the framed composite."""
    start = int(image.shape[0] * top_fraction)
    return image[start:, ...]


# ================================================================
# FIGURE
# ================================================================

fig = plt.figure(
    figsize=(15.5, 8.2)
)

gs = fig.add_gridspec(
    2,
    2,
    width_ratios=[1.08, 1.0],
    height_ratios=[1.0, 1.0],
    wspace=0.06,
    hspace=0.05,
)


ax_a = fig.add_subplot(
    gs[:, 0]
)

ax_b = fig.add_subplot(
    gs[0, 1]
)

ax_c = fig.add_subplot(
    gs[1, 1]
)


for ax, label in [
    (ax_a, "A"),
    (ax_b, "B"),
    (ax_c, "C"),
]:
    ax.imshow(
        images[label]
    )

    ax.axis("off")

    ax.text(
        0.01,
        0.99,
        label,
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=19,
        fontweight="bold",
        bbox={
            "facecolor": "white",
            "alpha": 0.90,
            "edgecolor": "none",
            "pad": 3,
        },
    )


fig.suptitle(
    "Deep-ensemble uncertainty and selective prediction",
    fontsize=17,
    fontweight="bold",
    y=0.985,
)


PNG = (
    OUT
    / "final_uncertainty_publication.png"
)

PDF = (
    OUT
    / "final_uncertainty_publication.pdf"
)


fig.savefig(
    PNG,
    dpi=300,
    bbox_inches="tight",
)

fig.savefig(
    PDF,
    bbox_inches="tight",
)

plt.close(fig)


# ================================================================
# FRAMED "PRETTY" RELEASE COMPOSITE
# ================================================================

pretty_png = OUT / "final_uncertainty_publication_pretty.png"
pretty_pdf = OUT / "final_uncertainty_publication_pretty.pdf"

fig = plt.figure(figsize=(16, 9), facecolor="white")
fig.suptitle(
    "Deep-ensemble uncertainty and selective prediction",
    fontsize=22,
    fontweight="bold",
    y=0.975,
)

# Outer panel rectangles in figure coordinates.
panel_specs = {
    "A": (0.02, 0.08, 0.50, 0.80),
    "B": (0.54, 0.50, 0.44, 0.38),
    "C": (0.54, 0.08, 0.44, 0.38),
}

panel_titles = {
    "A": ("Uncertainty is associated with prediction error",
          "Spearman ρ = 0.519"),
    "B": ("Prediction error increases with model uncertainty", None),
    "C": ("Selective prediction improves performance", None),
}

for label, (left, bottom, width, height) in panel_specs.items():
    background = FancyBboxPatch(
        (left, bottom),
        width,
        height,
        transform=fig.transFigure,
        boxstyle="round,pad=0.008,rounding_size=0.012",
        linewidth=1.2,
        edgecolor="#d7e4f3",
        facecolor="#f8fbff",
        zorder=0,
    )
    fig.add_artist(background)

    fig.text(
        left + 0.018,
        bottom + height - 0.045,
        label,
        ha="center",
        va="center",
        fontsize=17,
        fontweight="bold",
        bbox={
            "boxstyle": "round,pad=0.28",
            "facecolor": "#e4f2ff",
            "edgecolor": "none",
        },
    )

    title, subtitle = panel_titles[label]
    fig.text(
        left + 0.055,
        bottom + height - 0.045,
        title,
        ha="left",
        va="center",
        fontsize=15 if label == "A" else 13.5,
        fontweight="bold",
    )

    if subtitle:
        fig.text(
            left + width / 2,
            bottom + height - 0.080,
            subtitle,
            ha="center",
            va="center",
            fontsize=13,
        )

# Axes holding cropped source panels.
ax_a = fig.add_axes([0.055, 0.14, 0.43, 0.62])
ax_b = fig.add_axes([0.62, 0.56, 0.30, 0.24])
ax_c = fig.add_axes([0.60, 0.15, 0.33, 0.24])

for ax, label in [(ax_a, "A"), (ax_b, "B"), (ax_c, "C")]:
    ax.imshow(crop_panel_title(images[label]))
    ax.axis("off")

fig.savefig(
    pretty_png,
    dpi=300,
    bbox_inches="tight",
    facecolor="white",
)
fig.savefig(
    pretty_pdf,
    bbox_inches="tight",
    facecolor="white",
)
plt.close(fig)


print("=" * 90)
print("UNCERTAINTY PUBLICATION FIGURE")
print("=" * 90)

print()
print("Panel A : uncertainty vs absolute error")
print("Panel B : error across uncertainty deciles")
print("Panel C : selective prediction / abstention")
print()

print("Scientific values retained:")
print("Spearman rho = +0.518948")
print("Baseline MAE  = 0.116846")
print("Baseline R2   = 0.718138")
print("Reject 20% MAE = 0.084374")
print("Reject 20% R2  = 0.826913")
print()

print("Saved:", PNG)
print("Saved:", PDF)
print("Saved:", pretty_png)
print("Saved:", pretty_pdf)
print()
print("DONE")
